[package]
name = "pso_cli"
version = "0.1.0"
description = "Runs a single particle swarm optimization experiment."
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
glam = { version = "0.30.9", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
pso = { path = "../pso" }
serde_json = "1.0.145"